version: '2'

services:
  node1:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'tompizmor/node-mt'
    environment:
      - DATABASE_HOST=mongodb-primary
      - DATABASE_PORT=27017
      - DATABASE_NAME=todo
      - DATABASE_USER=todo
      - DATABASE_PASSWORD=bitnami
    ports:
      - 8081:3000
    volumes:
      - ./public:/mnt

  node2:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'tompizmor/node-mt'
    environment:
      - DATABASE_HOST=mongodb-primary
      - DATABASE_PORT=27017
      - DATABASE_NAME=todo
      - DATABASE_USER=todo
      - DATABASE_PASSWORD=bitnami
    ports:
      - 8082:3000
    volumes:
      - ./public:/mnt
